transformers:
    - name: "Buffer"
      no_struct: 1
     
    - name: "Amplifier"
      parameters:
        - name: "Gain"
          location: "gain"
          min: 0.0
          max: 2.0
          default: 1.0
    
    - name: "Distortion"
      parameters:
        - name: "Gain"
          default: 2.5
          min: 0.0
          max: 5.0
          smoothing: "instant"
        
        - name: "Wet Mix"
          default: 0.7
          type: mix
        
        - name: "High Mix"
          default: 0.333
          type: mix
        
        - name: "Mid Mix"
          default: 0.333
          type: mix
        
        - name: "Bass Mix"
          default: 0.333
          type: mix
        
        - name: "Mid Cutoff"
          default: 1000.0
          min: 1000.0
          max: 5000.0
        
        - name: "Bass Cutoff"
          default: 100.0
          min: 60.0
          max: 1000.0
         
        - name: "Ratio"
          default: 0.1
          min: 0.0
          max: 0.5
          smoothing: "instant"
    
