transformers:
    - name: "Buffer"
      no_struct: 1
     
    - name: "Amplifier"
      parameters:
        - name: "Gain"
          location: "gain"
          min: 0.0
          max: 2.0
          default: 1.0
    
    - name: "Mixer"
      hidden: True
      n_inputs: 2
      n_outputs: 1
      parameters:
       - name: "Ratio"
         default: 0.5
         min: 0.0
         max: 1.0
    
    - name: "Biquad"
      hidden: True
      parameters:
       - name: "Cutoff"
         default: 440.0
         min: 0.0
         max: 5000.0
         
       - name: "Bandwidth"
         default: 200.0
         min: 0.0
         max: 1000.0
       
       - name: "Gain (dB)"
         location: db_gain
         default: 0.0
         min: -3.0
         max:  3.0
    
    - name: "Distortion"
      parameters:
        - name: "Gain"
          default: 2.5
          min: 0.0
          max: 5.0
          smoothing: "instant"
        
        - name: "Wet Mix"
          default: 0.7
          type: mix
        
        - name: "High Mix"
          default: 0.333
          type: mix
        
        - name: "Mid Mix"
          default: 0.333
          type: mix
        
        - name: "Bass Mix"
          default: 0.333
          type: mix
        
        - name: "Mid Cutoff"
          default: 1000.0
          min: 1000.0
          max: 5000.0
        
        - name: "Bass Cutoff"
          default: 100.0
          min: 60.0
          max: 1000.0
         
        - name: "Ratio"
          default: 0.1
          min: 0.0
          max: 0.5
          smoothing: "instant"
    
    - name: "Compressor"
      parameters:
      - name: "Ratio"
        default: 2.0
        min: 1.0
        max: 10.0
        
      - name: "Threshold"
        default: -5.0
        min: -30.0
        max:   0.0
        
      - name: "Attack"
        default: 30.0
        min: 0.01
        max: 250.0
        
      - name: "Release"
        default: 30.0
        min: 0.01
        max: 250.0
    
    - name: "Waveshaper"
      hidden: True
