#ifndef TRANSFORMER_DEFAULTS_H_
#define TRANSFORMER_DEFAULTS_H_

#define DEFAULT_AMP_GAIN 	1.0
#define DEFAULT_MIXER_RATIO 0.5

#define DEFAULT_BIQUAD_TYPE 		low_pass
#define DEFAULT_BIQUAD_CUTOFF		440.0
#define DEFAULT_BIQUAD_BANDWIDTH	100.0
#define DEFAULT_BIQUAD_DB_GAIN		0.0

#define DEFAULT_COMPRESSOR_RATIO 		2.0
#define DEFAULT_COMPRESSOR_THRESHOLD 	8.0
#define DEFAULT_COMPRESSOR_ATTACK		0.001
#define DEFAULT_COMPRESSOR_RELEASE		0.03

#define DEFAULT_DISTORTION_TYPE  		DISTORTION_TANH
#define DEFAULT_DISTORTION_GAIN	 		4.0
#define DEFAULT_DISTORTION_RATIO 		0.1
#define DEFAULT_DISTORTION_BASS_CUTOFF 	100.0
#define DEFAULT_DISTORTION_MID_CUTOFF 	1500.0
#define DEFAULT_DISTORTION_BASS_MIX		1.0/3.0
#define DEFAULT_DISTORTION_MID_MIX		1.0/3.0
#define DEFAULT_DISTORTION_HIGH_MIX		1.0/3.0
#define DEFAULT_DISTORTION_WET_MIX		0.7

#define DEFAULT_WAVESHAPER_FUNCTION 	identity_function
#define DEFAULT_WAVESHAPER_COEFFICIENT  1.0

#endif
