#ifndef M_ENG_TRANSITION_H_
#define M_ENG_TRANSITION_H_

#define TRANSITION_MONOBLOCK_COS2	0
#define TRANSITION_QUADBLOCK_COS2	1
#define TRANSITION_OCTOBLOCK_COS2	2
#define TRANSITION_TAIL				3

#define TAIL_NEW_FADE_IN_SAMPLES	256
#define TAIL_INPUT_FADE_SAMPLES		256

#endif
