name: "Envelope"
parameters:
- name: "Min Center"
  default: 200.0
  min: 50.0
  max: 500.0
  type: freq
 
- name: "Max Center"
  default: 2000.0
  min: 200.0
  max: 5000.0
  type: freq
 
- name: "Width"
  default: 0.25
  min: 0.1
  max: 1.0
 
- name: "Speed"
  default: 2.9
  min: 200.0
  max: 0.5
  units: ms
 
- name: "Sensitivity"
  default: 2.0
  min: 0.1
  max: 10.0
 
- name: "Smoothness"
  default: 0.5
  min: 0.0
  max: 1.0
