name: "Noise Suppressor"
has_reconfigure: false
parameters:
- name: "Threshold"
  default: -50
  min: -100
  max: -10
 
- name: "Max Reduction"
  default: -30
  min: 0
  max: -100
 
- name: "Ratio"
  default: 1.0
  min: 0.0
  max: 20.0
