#ifndef ERROR_CODES_H_
#define ERROR_CODES_H_

#define NO_ERROR						0
#define ERR_NULL_PTR					1
#define ERR_BAD_ARGS					2
#define ERR_SGTL5000_WRITE_FAIL 		3

#define ERR_ALLOC_FAIL					5

#define ERR_PIPELINE_NULL				4
#define ERR_PIPELINE_FULL				6
#define ERR_POSITION_ILLEGAL			7
#define ERR_POSITION_OCCUPIED			8

#define ERR_TRANSFORMER_MALFORMED		9
#define ERR_ARRAY_MALFORMED				10

#define ERR_POT_LINK_MALFORMED			11
#define ERR_SWITCH_LINK_MALFORMED		12

#define ERR_MUTEX_UNAVAILABLE			13

#define ERR_FIXED_ARRAY_FULL			14

#define ERR_BUSTED_ET_MSG				15
#define ERR_ET_MSG_BAD_REQUEST			16

#define ERR_QUEUE_FULL					17
#define ERR_LOOP_DETECTED				18

#define ERR_NODE_PRIVATE				19
#define ERR_PIPELINE_BUSTED				20

#define ERR_ET_MSG_INVALID				21

#define ERR_UNKNOWN_ERR					4999
#define ERR_UNIMPLEMENTED				5000

#endif
