#ifndef M_TRANSFORMER_ENUM_H_
#define M_TRANSFORMER_ENUM_H_

#define TRANSFORMER_BUFFER			0
#define TRANSFORMER_MIXER			1
#define TRANSFORMER_AMPLIFIER		2
#define TRANSFORMER_BIQUAD			3
#define TRANSFORMER_WAVESHAPER		4
#define TRANSFORMER_DISTORTION		5
#define TRANSFORMER_COMPRESSOR		6

#endif
